package adapters

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"errors"
	"fmt"
	"io"
	"strings"

	go_ora "github.com/sijms/go-ora/v2"

	"github.com/kndndrj/nvim-dbee/dbee/core"
	"github.com/kndndrj/nvim-dbee/dbee/core/builders"
)

// cursorData holds the results from a single REF CURSOR
type cursorData struct {
	name   string
	header core.Header
	rows   []core.Row
}

func filterCursorBindNames(binds map[string]string, cursorParams []string) map[string]string {
	if len(binds) == 0 || len(cursorParams) == 0 {
		return binds
	}

	cursorNames := make(map[string]bool, len(cursorParams))
	for _, param := range cursorParams {
		cursorNames[strings.ToUpper(strings.TrimSpace(param))] = true
	}

	filtered := make(map[string]string, len(binds))
	for name, value := range binds {
		if cursorNames[strings.ToUpper(strings.TrimSpace(name))] {
			continue
		}
		filtered[name] = value
	}
	return filtered
}

// executePLSQLWithCursor handles PL/SQL execution with REF CURSOR OUT parameters.
// The cursor results are returned as a proper ResultStream grid.
// Multiple cursors are displayed sequentially with separator rows.
// This is a worker function — it does NOT manage d.mu. The caller
// (executePLSQLLocked) owns the mutex via its defer.
func (d *oracleDriver) executePLSQLWithCursor(ctx context.Context, conn *sql.Conn, rewritePlan oracleBindRewritePlan, binds map[string]string) (core.ResultStream, error) {
	cursorParams := rewritePlan.cursorParams
	if len(cursorParams) == 0 {
		return nil, errors.New("no cursor parameters found")
	}
	if len(rewritePlan.cursorDriverNames) != len(cursorParams) {
		return nil, errors.New("cursor bind rewrite plan is incomplete")
	}

	// Create cursor variables and attach precomputed driver names.
	cursors := make([]go_ora.RefCursor, len(cursorParams))
	args := make([]any, 0, len(rewritePlan.cursorBindArgs)+len(cursorParams))
	args = append(args, rewritePlan.cursorBindArgs...)
	for i := range cursorParams {
		args = append(args, sql.Named(rewritePlan.cursorDriverNames[i], sql.Out{Dest: &cursors[i]}))
	}

	// Enable DBMS_OUTPUT only after all bind names are validated.
	_, err := conn.ExecContext(ctx, "BEGIN DBMS_OUTPUT.ENABLE(NULL); END;")
	if err != nil {
		if isSessionConnError(err) {
			d.resetSessionConnLocked()
		}
		return nil, fmt.Errorf("failed to enable DBMS_OUTPUT: %w", err)
	}

	// Add semicolon if needed
	execQuery := stripTrailingSQLPlusSlashTerminator(rewritePlan.rewrittenSQL)
	isCall := strings.HasPrefix(strings.ToUpper(strings.TrimSpace(execQuery)), "CALL ")
	if !isCall && !strings.HasSuffix(strings.TrimSpace(execQuery), ";") {
		execQuery += ";"
	}

	// Execute with all cursor OUT parameters
	_, err = conn.ExecContext(ctx, execQuery, args...)
	if err != nil {
		if isSessionConnError(err) {
			d.resetSessionConnLocked()
		}
		return nil, wrapOracleError(err, rewritePlan.mapping)
	}

	// Collect results from all cursors
	var allResults []cursorData
	for i, cursor := range cursors {
		result, err := collectCursorData(cursorParams[i], &cursor)
		if err != nil {
			if isSessionConnError(err) {
				d.resetSessionConnLocked()
			}
			return nil, wrapOracleError(fmt.Errorf("failed to read cursor %s: %w", cursorParams[i], err), rewritePlan.mapping)
		}
		allResults = append(allResults, result)
	}

	// Preserve DBMS_OUTPUT generated by the same PL/SQL execution.
	output, err := d.fetchDBMSOutputFromConn(ctx, conn)
	if err != nil {
		if isSessionConnError(err) {
			d.resetSessionConnLocked()
		}
		return nil, fmt.Errorf("failed to fetch DBMS_OUTPUT: %w", err)
	}
	outputLines := parseDBMSOutputLines(output)
	if len(outputLines) > 0 {
		outRows := make([]core.Row, 0, len(outputLines))
		for _, line := range outputLines {
			outRows = append(outRows, core.Row{line})
		}
		allResults = append(allResults, cursorData{
			name:   "dbms_output",
			header: core.Header{"DBMS_OUTPUT"},
			rows:   outRows,
		})
	}

	// Build combined ResultStream
	return buildMultiCursorResultStream(allResults), nil
}

// collectCursorData reads all rows from a cursor into memory
func collectCursorData(name string, cursor *go_ora.RefCursor) (cursorData, error) {
	ds, err := cursor.Query()
	if err != nil {
		return cursorData{}, err
	}
	defer ds.Close()

	cols := ds.Columns()
	header := make(core.Header, len(cols))
	for i, col := range cols {
		header[i] = col
	}

	var rows []core.Row
	for {
		rowBuffer := make([]driver.Value, len(cols))
		err := ds.Next(rowBuffer)
		if err != nil {
			if errors.Is(err, io.EOF) {
				break
			}
			return cursorData{}, err
		}
		row := make(core.Row, len(rowBuffer))
		for i, v := range rowBuffer {
			row[i] = v
		}
		rows = append(rows, row)
	}

	return cursorData{name: name, header: header, rows: rows}, nil
}

// buildMultiCursorResultStream creates a ResultStream from multiple cursor results.
// Each cursor section starts with a header row showing the cursor name.
func buildMultiCursorResultStream(results []cursorData) core.ResultStream {
	if len(results) == 0 {
		return builders.NewResultStreamBuilder().
			WithHeader(core.Header{"(no results)"}).
			WithNextFunc(func() (core.Row, error) { return nil, nil }, func() bool { return false }).
			Build()
	}

	// For single cursor, use simple format (no separator needed)
	if len(results) == 1 {
		idx := 0
		rows := results[0].rows
		return builders.NewResultStreamBuilder().
			WithHeader(results[0].header).
			WithNextFunc(
				func() (core.Row, error) {
					if idx >= len(rows) {
						return nil, nil
					}
					row := rows[idx]
					idx++
					return row, nil
				},
				func() bool { return idx < len(rows) },
			).
			Build()
	}

	// For multiple cursors, find max column count and build unified stream
	maxCols := 0
	for _, r := range results {
		if len(r.header) > maxCols {
			maxCols = len(r.header)
		}
	}

	// Build flattened rows: separator + header + data for each cursor
	var allRows []core.Row
	for i, r := range results {
		// Add separator row (except for first cursor)
		if i > 0 {
			sep := make(core.Row, maxCols)
			sep[0] = "───────────────"
			for j := 1; j < maxCols; j++ {
				sep[j] = ""
			}
			allRows = append(allRows, sep)
		}

		// Add cursor name row
		nameRow := make(core.Row, maxCols)
		nameRow[0] = fmt.Sprintf("▶ %s", strings.ToUpper(r.name))
		for j := 1; j < maxCols; j++ {
			nameRow[j] = ""
		}
		allRows = append(allRows, nameRow)

		// Add header row
		headerRow := make(core.Row, maxCols)
		for j := 0; j < maxCols; j++ {
			if j < len(r.header) {
				headerRow[j] = r.header[j]
			} else {
				headerRow[j] = ""
			}
		}
		allRows = append(allRows, headerRow)

		// Add data rows (pad if needed)
		for _, row := range r.rows {
			paddedRow := make(core.Row, maxCols)
			for j := 0; j < maxCols; j++ {
				if j < len(row) {
					paddedRow[j] = row[j]
				} else {
					paddedRow[j] = nil
				}
			}
			allRows = append(allRows, paddedRow)
		}
	}

	// Use first cursor's header as the stream header (for column count)
	streamHeader := make(core.Header, maxCols)
	for i := 0; i < maxCols; i++ {
		if i < len(results[0].header) {
			streamHeader[i] = results[0].header[i]
		} else {
			streamHeader[i] = fmt.Sprintf("COL%d", i+1)
		}
	}

	idx := 0
	return builders.NewResultStreamBuilder().
		WithHeader(streamHeader).
		WithNextFunc(
			func() (core.Row, error) {
				if idx >= len(allRows) {
					return nil, nil
				}
				row := allRows[idx]
				idx++
				return row, nil
			},
			func() bool { return idx < len(allRows) },
		).
		Build()
}
